# Usage:
#   docker-compose -p Elk up -d --force-recreate --build
version: '2'
services:
  elasticsearch:

    image: 'elasticsearch:7.6.1'
    restart: always
    volumes:
      - './data/elastic/share:/usr/share/elasticsearch/data'
      - './data/elastic/bin:/usr/bin/elasticsearch/data'

    environment:
#     - bootstrap.memory_lock=true
      - discovery.type=single-node
#  ulimits:
#    memlock:
#      soft: -1
#      hard: -1
#    nofile:
#      soft: 65536
#      hard: 65536
    ports:
      - "9400:9200"
      - "9300:9300"

  kibana:
    image: kibana:7.6.1
    ports:
      - "5601:5601"
    volumes:
      - './data/kibana/share:/usr/share/kibana/data'
      - './data/kibana/share:/usr/bin/kibana/data'
    environment:
#      SERVER_NAME: localhost
      elasticsearch.username: "admin"
      elasticsearch.password: "admin123"
      ELASTICSEARCH_URL: http://localhost:9400
#      xpack.monitoring.ui.container.elasticsearch.enabled: false
#      XPACK.SECURITY.ENABLED: false

#  MetricBeat:
#    image: docker.elastic.co/beats/metricbeat:7.6.2
#    container_name: MetricBeat
#    environment:
#      setup.kibana.host=localhost:5601
#      output.elasticsearch.hosts=["localhost:9200"]


#https://www.elastic.co/guide/en/beats/metricbeat/current/running-on-docker.html
